# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181229_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='operational',
            field=models.SmallIntegerField(choices=[(1, '取消订单'), (2, '去支付'), (3, '确认收货')], default=2, verbose_name='买家操作'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Address', verbose_name='收货地址'),
        ),
    ]
