# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
    ]
