# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.SmallIntegerField(choices=[(1, '普通会员'), (2, '白银会员'), (3, '黄金会员'), (4, '钻石会员')], default=1, verbose_name='会员等级'),
        ),
    ]
