# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
