# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='市')),
            ],
            options={
                'verbose_name': '市',
                'verbose_name_plural': '市',
                'db_table': 'tb_city',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10, verbose_name='省')),
            ],
            options={
                'verbose_name': '省',
                'verbose_name_plural': '省',
                'db_table': 'tb_province',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Province', verbose_name='省'),
        ),
    ]
