# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('aParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area', verbose_name='父级城市')),
            ],
            options={
                'verbose_name_plural': '地区',
                'db_table': 'tb_area',
                'verbose_name': '地区',
            },
        ),
    ]
